### ISSUE TITLE
Hoe In Mistlands

### ISSUE THREAD

**Issue by RussellMMO** [java-devil/OCDheim#1]
When using the hoe in the Mistlands biome, it turns the terrain to grass instead of the black marble terrain it has. While not a game-breaking bug, its visually annoying and not very befitting of a mod named OCDheim lol. 
Other than that, I'm def enjoying this mod so far.

**Comment by RussellMMO** [comment]
I should mention i installed from the Thunderstore using R2Modman as the manager. 
I also noticed it has conflicts with other snapping mods, but i expected that. 
Mostly just key bind conflicts, so it can be fixed on my side easily.
I'm Using Gizmo by comfy mods, and Valheim plus as my other 2 mods.

**Comment by java-devil** [comment]
I am aware.
I consider this serious.
(tar pits in The Plains work similarly BTW)

Fixing this will be surprisingly non-trivial. However I DO have this on my radar.
This issue will probably remain open for a while I'm afraid.

**Comment by RussellMMO** [comment]
Ah, ok! Thanks for the response and I'm looking forward to what you have planned with this mod!

**Comment by java-devil** [comment]
![obraz](https://user-images.githubusercontent.com/94081319/208319457-b56c9072-4cbe-4f07-9d9e-e04236cc274f.png)

 I lied! Seems this actually is not as non-trivial to fix as as I made it sound to be ;)
 Unless testing uncovers something shockingly horrible... new release incoming.

**Comment by java-devil** [comment]
Should be solved in released v0.1.2 :)

**Comment by java-devil** [comment]
Should be solved in released v0.1.2 :)
