### ISSUE TITLE
Possible conflict with PlantEverything

### ISSUE THREAD

**Issue by ncottrill** [java-devil/OCDheim#13]
The mod "Plant Everything" by Advize allows the user to equip the cultivator and press the middle mouse button in order to remove a pickable item. After installing OCDHeim, this middle mouse button function doesn't work.

I tried checking for alt keybind but there isn't any setting for keybinds in the PlantEverything config.

Any suggestions?

**Comment by java-devil** [comment]
Normally I would say that compatibility with other mods will be a priority a couple of months into the development life-cycle. However, this sounds weird enough (neither does OCDheim use the middle mouse button, nor does Advize's mod use ALT AFAIK) and serious enough for a small inquiry ;)

Thank You once more :)

**Comment by ncottrill** [comment]
I have pinpointed this issue, as well. The problem was with the Heightunlimited Mod. This particular mod (Height mod) also introduced memory leaks. I apologize for the length of time to get back to you on these 2 issues. It took awhile for me to debug.

**Comment by java-devil** [comment]
Am I too optimistic to conclude that this issue could be considered closed from your perspective?
