### ISSUE TITLE
Version incompatible.

### ISSUE THREAD

**Issue by Kyamon** [java-devil/OCDheim#4]
Both my friend and I have version 0.1.1, but when they try to join me it tells them I have version 0.1.0 and disconnects them.

**Comment by java-devil** [comment]
This is my manual screw up. The Thunderstore version 0.1.1 thinks internally it's version 0.1.0. Once I finish working on the release automation this issue won't be possible anymore. Interestingly BepInEx is configured to require only minor version parity anyway...

Version 0.1.2 is releasing Soon™ and will incidentally resolve this problem.

**Comment by java-devil** [comment]
Should be solved in released v0.1.2 :)
