### ISSUE TITLE
doesn't load textures when placed in his own file

### ISSUE THREAD

**Issue by SadScourge** [java-devil/OCDheim#5]
i did try to install this mod in his own file to keep my plugins folder clean and the mod didn't seem to work as intended
(also it didn't unlock the new craft when i did that)
it worked perfectly when i placed everything in the plugins folder so it's not a big issue

**Comment by java-devil** [comment]
Which version of the mod are you running?

To paraphrase: you copied OCDheim (the ocdheim.dll file as well as all the .png files) to its own directory inside of the "plugins" directory? If so - this issue should be resolved since version 0.1.1 :)

**Comment by SadScourge** [comment]
oh yeah i'm running version 0.1.0 i'm glad this is fixed
btw thanks for creating this beautiful mod

**Comment by SadScourge** [comment]
i just tested and it work perfectly
